### ISSUE TITLE
aktualisierung

### ISSUE THREAD

**Issue by wp-seth** [latextemplates/diplomarbeit-mit-latex#1]
cool, dass du den alten schinken ausgegraben und vergittet hast. ich habe am wochenende auf meiner festplatte noch eine lokale version des svn repos gefunden, die aber mangels svn-server ja nun wertlos geworden ist. selbst die history ist ja bei svn nur zentral gespeichert. :-/

jedenfalls ist mir aufgefallen, dass die alten source-files nicht ohne weiteres compilieren und habe deswegen das dokument zumindest soweit ueberarbeitet, dass die anzahl der errors 0 und die der warnings (inkl. over-/underfull boxes) nun 1 ist. inhaltlich sind auch noch einige sachen zu ueberarbeiten, weil sie obsolet sind. da habe ich bisher nur kleinigkeiten abgeaendert (z.b. den source-url, da der originalort ja nicht mehr existiert). wie gehen wir vor? soll ich das repo forken und einen pull request erstellen?

**Comment by koppor** [comment]
Gerne 🌞 

Kommt drauf an. Möchtest du das Repo mit History sehen oder ohne? Falls mit History, kann ich das SVN gerne zu git konvertieren. Hab ich schon öfters gemacht. Falls ohne History, dann einfach PR und passt schon :-)

**Comment by koppor** [comment]
Side comment: Hatte Tobias (dir?) im Juni 2015 versucht eine E-mail zu schreiben, aber sie kam mit "550 relay not permitted" zurück.

Wollte dich auch fragen, ob du evtl. die Lizenz des Textes ändern wollen würdest, so dass es einfacher ist, es in andere Werke zu integrieren. So `CC-BY` oder `CC-BY-SA`. Können uns gerne auch privater austauschen. Meine Email findest du in meinem GitHub-Profil.

**Comment by wp-seth** [comment]
- ich bin nicht tobias, sondern hab nur mal 2008 das mathe-kapitel etwas ueberarbeitet.
- repo mit history: waere cool, wenn wir die originalhistory importieren koennten, aber ohne das zentrale repo bekommen wir das wohl nicht hin. lokale versionen haben ja kaum daten ueber das eigentliche repo. und das ist schon lange offline. (die von mir eingangs angesprochenen wenigen aenderungen sind noch nicht versioniert.)
- die alte domain von tobias scheint tot zu sein, aber ich denke, ich habe eine alternative e-mail-adresse von ihm gefunden (die ich aus spam-/datenschutzgruenden nicht hier nennen werde). ich schreib dazu ne e-mail.
- der andere hauptautor scheint sogar ein github-profil zu haben: @akkinitsch
- mind. die beiden hauptautoren muesste man bei einem lizenzwechsel fragen. evtl. auch die anderen helfer (im dml-dokument werden ein paar genannt.)

**Comment by wp-seth** [comment]
wie ist denn hier nun der stand? wurde mein PR mal angeschaut?

**Comment by wp-seth** [comment]
wenn du mir rechte fuer dieses repo gibst, koennte ich die aenderungen direkt hier in branches machen. faend ich etwas uebersichtlicher.

**Comment by wp-seth** [comment]
danke, scheint jedoch noch nicht zu funzen:
```
ERROR: Permission to texdoc/diplomarbeit-mit-latex.git denied to wp-seth.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```
