### ISSUE TITLE
Fehler im Codebeispiel auf Seite 71

### ISSUE THREAD

**Issue by Jackd4w** [latextemplates/diplomarbeit-mit-latex#12]
Da müsste es \sum_{i=0}^n\frac 1{i!} \xrightarrow{n\rightarrow\infty} e heißen um die gezeigte Übersetzung zu bekommen.

**Comment by koppor** [comment]
Pull request welcome 😇 

#hacktoberfest

**Comment by wp-seth** [comment]
<s>hmm, ich sehe da keinen fehler. ausserdem ist bei mir der code auf seite 73. hast du evtl. ein altes dokument vorliegen @Jackd4w? welche version steht denn ganz oben auf der ersten seite?</s>
auszug aus dem code:
https://github.com/texdoc/diplomarbeit-mit-latex/blob/7c85d0166d7cf17a57dbfc0006e59e6a750def4a/chapters/formeln.tex#L393-L403

edit: ahhh, verflucht! jetzt erst, nach dem speichern hier, seh ich's! left vs. right

**Comment by koppor** [comment]
Siehe https://github.com/texdoc/diplomarbeit-mit-latex/blob/gh-pages/diplomarbeit_mit_latex.pdf für aktuelles PDF.

**Comment by wp-seth** [comment]
oh, interessant. offenbar sind die abstaende ueber den listings in deinem pdf viel kleiner als bei mir. erst wenn ich die leerzeilen im code loesche, sind die abstaende gleich.

**Comment by Jackd4w** [comment]
Erster Beitrag, deswegen bin ich mir noch nicht ganz so sicher wie das mit den Requests geht :')
Sorry das die Beschreibung so unpräzise war, versuche das in Zukunft präziser zu machen.

**Comment by wp-seth** [comment]
zu pull requests findet man relativ schnell brauchbare anleitungen z.b.: https://reflectoring.io/github-fork-and-pull/
in diesem fall ist es nicht mehr noetig. ich habe gestern bereits einen pull request #13 erstellt und warte nur noch auf ein review von @koppor.
zur praezision: ja, praeziser waere zwar besser, andererseits hatte ich offenbar einfach tomaten auf den augen. also: kein stress.
