### ISSUE TITLE
fertig-compiliertes pdf-file sollte auch verfuegbar sein, allein schon fuer die latex-installationsanleitung

### ISSUE THREAD

**Issue by wp-seth** [latextemplates/diplomarbeit-mit-latex#14]
aktuell wird hier nur der source-code angeboten. 
die latex-installationsanleitung steht allerdings nur im fertig-compilierten pdf.
anfaenger, fuer die das dokument ja geschrieben ist, werden somit schwierigkeiten haben.

deshalb sollte irgendwo das fertig-compilierte pdf-file verfuegbar und in der readme-datei verlinkt sein.
gaebe es einen besseren ort als das repo fuer das pdf? sollte man gh-pages dafuer nutzen?

**Comment by wp-seth** [comment]
aha! :-)
https://github.com/texdoc/diplomarbeit-mit-latex/raw/gh-pages/diplomarbeit_mit_latex.pdf

**Comment by koppor** [comment]
Hatte wohl ein copy'n'paste fehler im github workflow - unter https://github.com/texdoc/diplomarbeit-mit-latex/commit/36433ea92c80fbea10c821f1b3f29a07ac1cd4c3 gefixed.

Homepage gerade fertig geworden: https://texdoc.github.io/diplomarbeit-mit-latex/

Inhalte können hier rein gepackt werden: https://github.com/texdoc/diplomarbeit-mit-latex/blob/master/gh-pages/index.md
