### ISSUE TITLE
\ref durch \cref (cleverref) ersetzen

### ISSUE THREAD

**Issue by wp-seth** [latextemplates/diplomarbeit-mit-latex#21]
\ref sollte niemand mehr benutzen (muessen). \cref ist in jeglicher hinsicht ueberlegen.

**Comment by koppor** [comment]
Minimalcode: https://github.com/latextemplates/generator-latex-template/blob/master/generators/app/templates/cleveref.preamble.de.tex

**Comment by wp-seth** [comment]
die paket-optionen passen (wobei capitalize wohl ueberfluessig ist). die anderen sollte man eigentlich nicht brauchen, weil cleverref auch deutsch kann. nur listings musste ich ergaenzen:
```latex
\usepackage[capitalise,nameinlink,noabbrev]{cleveref}
\crefname{lstlisting}{\lstlistingname}{\lstlistingname}
```

**Comment by koppor** [comment]
`capitalize` ist für englische Dokumente wichtig.

**Comment by wp-seth** [comment]
> `capitalize` ist für englische Dokumente wichtig.

ich weiss, wobei es auch nicht immer so ist. es gibt im englischen keine einheitliche konvention.
