### ISSUE TITLE
Seite 14, 2.1.1. Herunterladen des Setup-Programms. MiKTeX Link funktioniert nicht.

### ISSUE THREAD

**Issue by Leonetienne** [latextemplates/diplomarbeit-mit-latex#26]
https://www.miktex.org/  ist anscheinend veraltet und funktioniert nicht mehr.
https://miktex.org/ funktioniert.

**Comment by wp-seth** [comment]
danke fuer den hinweis.
ja, seltsam. http://www.miktex.org/ leitet per 301 nach https://miktex.org/ weiter. aber https://www.miktex.org/ ist ziemlich tot.
