### ISSUE TITLE
changelog

### ISSUE THREAD

**Issue by wp-seth** [latextemplates/diplomarbeit-mit-latex#8]
Schließlich fände ich es noch gut, wenn ein CHANGELOG wie bei keep-a-changelog geführt würde (statt LaTeX). Hier ein Beispiel: https://github.com/latextemplates/scientific-thesis-template/blob/master/CHANGELOG.md

_Originally posted by @koppor in https://github.com/texdoc/diplomarbeit-mit-latex/pull/2#issuecomment-690686607_

**Comment by wp-seth** [comment]
ja, ich denke auch, dass das heutzutage nicht mehr im generierten dokument enthalten sein sollte, sondern dass eine meta-datei sinnvoller ist. ok, dann verschieben wir das change log also in eine datei.

btw. ich versuche mich im wesentlichen an https://karma-runner.github.io/5.2/dev/git-commit-msg.html zu halten (mit den ergaenzungen `ci`, `build` und `perf`), sodass eine halb-automatische erstellung eines changelogs moeglich sein sollte (wenn sich alle beteiligten daran halten).

**Comment by koppor** [comment]
Finde diese Art von Commit-Nachrichten gut.

Allerdings könnten sie "Anfänger" abschrecken. Würde das nicht erzwingen. Lieber etwas Mehraufwand auf unserer Seite. Nichtsdestoweniger finde ich https://github.com/git-chglog/git-chglog als Tool (auf den ersten Blick) ganz gut.
